apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: brian-bootstrap-appsets
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: brian-test
  source:
    path: .
    repoURL: https://github.com/Axory/test-argo-cd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true  #cleaned up if removed from the source
      selfHeal: true  #ensures resources are up-to-date
    syncOptions:
    - CreateNamespace=true